In [3]:
import os
import numpy as np
from joblib import load, dump
import pandas as pd

In [4]:
primitive_recommendations = load('../cache/primitive_recommendations.joblib')

In [9]:
a = np.array([[1, 2], [2, 3]])
np.unique(a)

array([1, 2, 3])

In [11]:
flat_pr = {}

In [12]:
for user, value in primitive_recommendations.items():
    flat_pr[user] = np.unique(value)

In [14]:
dump(flat_pr, '../cache/flat_pr.joblib')

['../cache/flat_pr.joblib']

In [2]:
PATH = '../data/movielens/1m/'
CLEAN_PATH = os.path.join(PATH, 'clean')

In [3]:
test_data =  pd.read_csv(os.path.join(CLEAN_PATH, 'test_data.csv'), index_col='userId')

In [4]:
test_data

1    2    3    4    5    6    7    8    9   10  ...  3943  3944  \
userId                                                    ...               
5530    3.0  2.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  0.0  ...   0.0   0.0   
711     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
4924    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2154    4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1273    3.0  0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  ...   0.0   0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   
1216    0.0  0.0  0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
2081    0.0  0.0  0.0  0.0  0.0  5.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
5674    5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
3936    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   
1095    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   

        3945  3946  3947  3948  3949  3950  3951  3952  
userId                                                  
5530     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
711      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4924     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2154     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1273     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...      ...   ...   ...   ...   ...   ...   ...   ...  
1216     0.0   0.0   5.0   0.0   0.0   0.0   0.0   0.0  
2081     0.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0  
5674     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3936     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1095     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[1208 rows x 3706 columns]

In [5]:
recommendations = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]] * len(test_data))

In [6]:
recommendations

array([[ 1,  2,  3, ...,  8,  9, 10],
       [ 1,  2,  3, ...,  8,  9, 10],
       [ 1,  2,  3, ...,  8,  9, 10],
       ...,
       [ 1,  2,  3, ...,  8,  9, 10],
       [ 1,  2,  3, ...,  8,  9, 10],
       [ 1,  2,  3, ...,  8,  9, 10]])

In [7]:
a = test_data.iloc[0]

In [31]:
a

1       3.0
2       2.0
3       0.0
4       0.0
5       0.0
       ... 
3948    0.0
3949    0.0
3950    0.0
3951    0.0
3952    0.0
Name: 5530, Length: 3706, dtype: float64

In [38]:
b = a[a.index.astype(int).isin(recommendations[0])]

In [42]:
b[b != 0].shape[0]

3

In [51]:
(recommendations == 2).sum()

1208

In [66]:
(test_data[movie_id] != 0).sum()

79

In [5]:
recommendations = np.random.choice(test_data.columns.astype(int), size=(test_data.shape[0], 10))

In [6]:
recommendations

array([[ 946, 2108, 3147, ..., 3847, 2582, 3155],
       [1667, 2026,  671, ..., 2591,  697, 2920],
       [1604, 1529, 2859, ..., 2807, 1464, 2384],
       ...,
       [1933,  304,  172, ...,   70, 2922, 2143],
       [3305,  988, 3757, ..., 2947, 3573, 3054],
       [2058, 1916,  718, ..., 2294,  121,  140]], dtype=int64)

In [21]:
(recommendations == int(3))

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [7]:
movies_nov = pd.Series(np.zeros(len(test_data.columns)), index=test_data.columns, dtype=np.float32)
for movie_id in test_data.columns:
    recommended_fraction = (recommendations == int(movie_id)).sum()
    not_interacted_fraction = (test_data[movie_id] == 0).sum() + 1e-10
#     print(recommended_fraction, not_interacted_fraction, 1 - (recommended_fraction / not_interacted_fraction))
    movies_nov[movies_nov.index == movie_id] =  1 - (recommended_fraction / not_interacted_fraction)

In [8]:
movies_nov = (movies_nov - movies_nov.min()) / (movies_nov.max() - movies_nov.min())

In [11]:
recommendations[0]

array([ 946, 2108, 3147,  657, 1518,  314, 3362, 3847, 2582, 3155],
      dtype=int64)

In [15]:
movies_nov

1       0.722540
2       0.897618
3       1.000000
4       0.353426
5       0.428790
          ...   
3948    0.792102
3949    0.338806
3950    0.909097
3951    0.728665
3952    0.807577
Length: 3706, dtype: float32

In [19]:
movies_nov[movies_nov.index.astype(int).isin(recommendations[0])].mean()

0.6136652

In [16]:
movies_nov.index

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       ...
       '3943', '3944', '3945', '3946', '3947', '3948', '3949', '3950', '3951',
       '3952'],
      dtype='object', length=3706)